### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by comlaterra** [ifndefdeadmau5/react-floating-button-menu#10]
Following the README instructions:
```
git clone https://github.com/ifndefdeadmau5/react-floating-button-menu.git
cd react-floating-button-menu
npm install
cd docs
npm install
npm start
```
The following error appears:
```
      this.log.error("Invalid options type for " + alias, TypeError);
               ^

TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:266:16)
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:371:14
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:398:22
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:387:20)
    at OptionManager.mergePresets (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:370:10)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:330:14)
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:371:14
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:392:24
    at Array.map (<anonymous>)```

Using NPM 6.7.0

**Comment by ifndefdeadmau5** [comment]
That's weird, have you tried flushing `node_modules` and run `npm install` again?

**Comment by comlaterra** [comment]
M?
Why would I need to do that if the project starts from scratch?
I can check it out. definitely

**Comment by comlaterra** [comment]
Nah, as expected, still failing.
Maybe it helps:
Node version: 11.12.0
NPM version: 6.7.0
